/*
 * api/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: version not set
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_client

// Represents a union of types.
type MlMetadataUnionArtifactStructType struct {
	// An artifact struct matches this type if it matches any of the candidates. If candidates is empty, this is a bottom type (matches no artifacts).
	Candidates []MlMetadataArtifactStructType `json:"candidates,omitempty"`
}
