/*
 * api/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: version not set
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_client

// MlMetadataEventType : Events distinguish between an artifact that is written by the execution (possibly as a cache), versus artifacts that are part of the declared output of the Execution. For more information on what DECLARED_ means, see the comment on the message.
type MlMetadataEventType string

// List of ml_metadataEventType
const (
	DECLARED_OUTPUT MlMetadataEventType = "DECLARED_OUTPUT"
	DECLARED_INPUT  MlMetadataEventType = "DECLARED_INPUT"
	INPUT           MlMetadataEventType = "INPUT"
	OUTPUT          MlMetadataEventType = "OUTPUT"
)
