/*
 * api/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: version not set
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_client

type ApiCreateArtifactResponse struct {
	Artifact MlMetadataArtifact `json:"artifact,omitempty"`
}
