/*
 * api/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: version not set
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_client

// A value in properties.
type MlMetadataValue struct {
	IntValue string `json:"int_value,omitempty"`
	DoubleValue float64 `json:"double_value,omitempty"`
	StringValue string `json:"string_value,omitempty"`
}
