/*
 * api/service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: version not set
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi_client

type ApiGetExecutionTypeResponse struct {
	ExecutionType MlMetadataExecutionType `json:"execution_type,omitempty"`
}
