# coding: utf-8

"""
    api/service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.api_create_artifact_type_response import ApiCreateArtifactTypeResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestApiCreateArtifactTypeResponse(unittest.TestCase):
    """ApiCreateArtifactTypeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApiCreateArtifactTypeResponse(self):
        """Test ApiCreateArtifactTypeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.api_create_artifact_type_response.ApiCreateArtifactTypeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
