apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metadata-watcher
  labels:
    component: watcher
spec:
  replicas: 1
  selector:
    matchLabels:
      component: watcher
  template:
    metadata:
      labels:
        component: watcher
    spec:
      containers:
      - name: container
        image: gcr.io/kubeflow-images-public/metadata/watcher:latest
        command: ["./watcher/watcher",
                  "-metadata_service=http://metadata-service.kubeflow:8080",
                  "-resourcelist=watcher/dockerfiles/resource_list.json"]
