# coding: utf-8

# flake8: noqa

"""
    api/service.proto

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: version not set
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.metadata_service_api import MetadataServiceApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.api_artifact_type import ApiArtifactType
from swagger_client.models.api_create_artifact_type_response import ApiCreateArtifactTypeResponse
from swagger_client.models.api_double_type import ApiDoubleType
from swagger_client.models.api_get_artifact_type_response import ApiGetArtifactTypeResponse
from swagger_client.models.api_int_type import ApiIntType
from swagger_client.models.api_list_artifact_types_response import ApiListArtifactTypesResponse
from swagger_client.models.api_namespace import ApiNamespace
from swagger_client.models.api_string_type import ApiStringType
from swagger_client.models.api_type import ApiType
