# coding: utf-8

"""
    api/service.proto

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: version not set
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ApiListEventsResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'events': 'list[MlMetadataEvent]',
        'artifacts': 'dict(str, MlMetadataArtifact)',
        'executions': 'dict(str, MlMetadataExecution)'
    }

    attribute_map = {
        'events': 'events',
        'artifacts': 'artifacts',
        'executions': 'executions'
    }

    def __init__(self, events=None, artifacts=None, executions=None):  # noqa: E501
        """ApiListEventsResponse - a model defined in OpenAPI"""  # noqa: E501

        self._events = None
        self._artifacts = None
        self._executions = None
        self.discriminator = None

        if events is not None:
            self.events = events
        if artifacts is not None:
            self.artifacts = artifacts
        if executions is not None:
            self.executions = executions

    @property
    def events(self):
        """Gets the events of this ApiListEventsResponse.  # noqa: E501


        :return: The events of this ApiListEventsResponse.  # noqa: E501
        :rtype: list[MlMetadataEvent]
        """
        return self._events

    @events.setter
    def events(self, events):
        """Sets the events of this ApiListEventsResponse.


        :param events: The events of this ApiListEventsResponse.  # noqa: E501
        :type: list[MlMetadataEvent]
        """

        self._events = events

    @property
    def artifacts(self):
        """Gets the artifacts of this ApiListEventsResponse.  # noqa: E501


        :return: The artifacts of this ApiListEventsResponse.  # noqa: E501
        :rtype: dict(str, MlMetadataArtifact)
        """
        return self._artifacts

    @artifacts.setter
    def artifacts(self, artifacts):
        """Sets the artifacts of this ApiListEventsResponse.


        :param artifacts: The artifacts of this ApiListEventsResponse.  # noqa: E501
        :type: dict(str, MlMetadataArtifact)
        """

        self._artifacts = artifacts

    @property
    def executions(self):
        """Gets the executions of this ApiListEventsResponse.  # noqa: E501


        :return: The executions of this ApiListEventsResponse.  # noqa: E501
        :rtype: dict(str, MlMetadataExecution)
        """
        return self._executions

    @executions.setter
    def executions(self, executions):
        """Sets the executions of this ApiListEventsResponse.


        :param executions: The executions of this ApiListEventsResponse.  # noqa: E501
        :type: dict(str, MlMetadataExecution)
        """

        self._executions = executions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiListEventsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
