// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/api.proto

package api

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PropertyType int32

const (
	PropertyType_UNKNOWN PropertyType = 0
	PropertyType_INT     PropertyType = 1
	PropertyType_DOUBLE  PropertyType = 2
	PropertyType_STRING  PropertyType = 3
)

var PropertyType_name = map[int32]string{
	0: "UNKNOWN",
	1: "INT",
	2: "DOUBLE",
	3: "STRING",
}

var PropertyType_value = map[string]int32{
	"UNKNOWN": 0,
	"INT":     1,
	"DOUBLE":  2,
	"STRING":  3,
}

func (x PropertyType) String() string {
	return proto.EnumName(PropertyType_name, int32(x))
}

func (PropertyType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

type Workspace struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Workspace) Reset()         { *m = Workspace{} }
func (m *Workspace) String() string { return proto.CompactTextString(m) }
func (*Workspace) ProtoMessage()    {}
func (*Workspace) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{0}
}

func (m *Workspace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Workspace.Unmarshal(m, b)
}
func (m *Workspace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Workspace.Marshal(b, m, deterministic)
}
func (m *Workspace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Workspace.Merge(m, src)
}
func (m *Workspace) XXX_Size() int {
	return xxx_messageInfo_Workspace.Size(m)
}
func (m *Workspace) XXX_DiscardUnknown() {
	xxx_messageInfo_Workspace.DiscardUnknown(m)
}

var xxx_messageInfo_Workspace proto.InternalMessageInfo

func (m *Workspace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ArtifactType struct {
	Id                   int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Properties           map[string]PropertyType `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=api.PropertyType"`
	Description          string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ArtifactType) Reset()         { *m = ArtifactType{} }
func (m *ArtifactType) String() string { return proto.CompactTextString(m) }
func (*ArtifactType) ProtoMessage()    {}
func (*ArtifactType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{1}
}

func (m *ArtifactType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArtifactType.Unmarshal(m, b)
}
func (m *ArtifactType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArtifactType.Marshal(b, m, deterministic)
}
func (m *ArtifactType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArtifactType.Merge(m, src)
}
func (m *ArtifactType) XXX_Size() int {
	return xxx_messageInfo_ArtifactType.Size(m)
}
func (m *ArtifactType) XXX_DiscardUnknown() {
	xxx_messageInfo_ArtifactType.DiscardUnknown(m)
}

var xxx_messageInfo_ArtifactType proto.InternalMessageInfo

func (m *ArtifactType) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ArtifactType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ArtifactType) GetProperties() map[string]PropertyType {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *ArtifactType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type ExecutionType struct {
	Id                   int64                   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TypeProperties       map[string]PropertyType `protobuf:"bytes,3,rep,name=type_properties,json=typeProperties,proto3" json:"type_properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3,enum=api.PropertyType"`
	Description          string                  `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *ExecutionType) Reset()         { *m = ExecutionType{} }
func (m *ExecutionType) String() string { return proto.CompactTextString(m) }
func (*ExecutionType) ProtoMessage()    {}
func (*ExecutionType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{2}
}

func (m *ExecutionType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecutionType.Unmarshal(m, b)
}
func (m *ExecutionType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecutionType.Marshal(b, m, deterministic)
}
func (m *ExecutionType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecutionType.Merge(m, src)
}
func (m *ExecutionType) XXX_Size() int {
	return xxx_messageInfo_ExecutionType.Size(m)
}
func (m *ExecutionType) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecutionType.DiscardUnknown(m)
}

var xxx_messageInfo_ExecutionType proto.InternalMessageInfo

func (m *ExecutionType) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ExecutionType) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ExecutionType) GetTypeProperties() map[string]PropertyType {
	if m != nil {
		return m.TypeProperties
	}
	return nil
}

func (m *ExecutionType) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Artifact struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeId               int64                `protobuf:"varint,2,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"`
	Uri                  string               `protobuf:"bytes,3,opt,name=uri,proto3" json:"uri,omitempty"`
	Properties           map[string]*Value    `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomProperties     map[string]*Value    `protobuf:"bytes,5,rep,name=custom_properties,json=customProperties,proto3" json:"custom_properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Name                 string               `protobuf:"bytes,6,opt,name=name,proto3" json:"name,omitempty"`
	Workspace            *Workspace           `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Labels               map[string]string    `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,9,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,10,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Artifact) Reset()         { *m = Artifact{} }
func (m *Artifact) String() string { return proto.CompactTextString(m) }
func (*Artifact) ProtoMessage()    {}
func (*Artifact) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{3}
}

func (m *Artifact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Artifact.Unmarshal(m, b)
}
func (m *Artifact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Artifact.Marshal(b, m, deterministic)
}
func (m *Artifact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Artifact.Merge(m, src)
}
func (m *Artifact) XXX_Size() int {
	return xxx_messageInfo_Artifact.Size(m)
}
func (m *Artifact) XXX_DiscardUnknown() {
	xxx_messageInfo_Artifact.DiscardUnknown(m)
}

var xxx_messageInfo_Artifact proto.InternalMessageInfo

func (m *Artifact) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Artifact) GetTypeId() int64 {
	if m != nil {
		return m.TypeId
	}
	return 0
}

func (m *Artifact) GetUri() string {
	if m != nil {
		return m.Uri
	}
	return ""
}

func (m *Artifact) GetProperties() map[string]*Value {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Artifact) GetCustomProperties() map[string]*Value {
	if m != nil {
		return m.CustomProperties
	}
	return nil
}

func (m *Artifact) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Artifact) GetWorkspace() *Workspace {
	if m != nil {
		return m.Workspace
	}
	return nil
}

func (m *Artifact) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Artifact) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Artifact) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

type Execution struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Workspace            *Workspace           `protobuf:"bytes,3,opt,name=workspace,proto3" json:"workspace,omitempty"`
	Properties           map[string]*Value    `protobuf:"bytes,4,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CustomProperties     map[string]*Value    `protobuf:"bytes,5,rep,name=custom_properties,json=customProperties,proto3" json:"custom_properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Labels               map[string]string    `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreateTime           *timestamp.Timestamp `protobuf:"bytes,7,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime           *timestamp.Timestamp `protobuf:"bytes,8,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	StartTime            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              *timestamp.Timestamp `protobuf:"bytes,10,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Execution) Reset()         { *m = Execution{} }
func (m *Execution) String() string { return proto.CompactTextString(m) }
func (*Execution) ProtoMessage()    {}
func (*Execution) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{4}
}

func (m *Execution) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Execution.Unmarshal(m, b)
}
func (m *Execution) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Execution.Marshal(b, m, deterministic)
}
func (m *Execution) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Execution.Merge(m, src)
}
func (m *Execution) XXX_Size() int {
	return xxx_messageInfo_Execution.Size(m)
}
func (m *Execution) XXX_DiscardUnknown() {
	xxx_messageInfo_Execution.DiscardUnknown(m)
}

var xxx_messageInfo_Execution proto.InternalMessageInfo

func (m *Execution) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Execution) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Execution) GetWorkspace() *Workspace {
	if m != nil {
		return m.Workspace
	}
	return nil
}

func (m *Execution) GetProperties() map[string]*Value {
	if m != nil {
		return m.Properties
	}
	return nil
}

func (m *Execution) GetCustomProperties() map[string]*Value {
	if m != nil {
		return m.CustomProperties
	}
	return nil
}

func (m *Execution) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Execution) GetCreateTime() *timestamp.Timestamp {
	if m != nil {
		return m.CreateTime
	}
	return nil
}

func (m *Execution) GetUpdateTime() *timestamp.Timestamp {
	if m != nil {
		return m.UpdateTime
	}
	return nil
}

func (m *Execution) GetStartTime() *timestamp.Timestamp {
	if m != nil {
		return m.StartTime
	}
	return nil
}

func (m *Execution) GetEndTime() *timestamp.Timestamp {
	if m != nil {
		return m.EndTime
	}
	return nil
}

type StringType struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringType) Reset()         { *m = StringType{} }
func (m *StringType) String() string { return proto.CompactTextString(m) }
func (*StringType) ProtoMessage()    {}
func (*StringType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{5}
}

func (m *StringType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringType.Unmarshal(m, b)
}
func (m *StringType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringType.Marshal(b, m, deterministic)
}
func (m *StringType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringType.Merge(m, src)
}
func (m *StringType) XXX_Size() int {
	return xxx_messageInfo_StringType.Size(m)
}
func (m *StringType) XXX_DiscardUnknown() {
	xxx_messageInfo_StringType.DiscardUnknown(m)
}

var xxx_messageInfo_StringType proto.InternalMessageInfo

func (m *StringType) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type IntType struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntType) Reset()         { *m = IntType{} }
func (m *IntType) String() string { return proto.CompactTextString(m) }
func (*IntType) ProtoMessage()    {}
func (*IntType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{6}
}

func (m *IntType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntType.Unmarshal(m, b)
}
func (m *IntType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntType.Marshal(b, m, deterministic)
}
func (m *IntType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntType.Merge(m, src)
}
func (m *IntType) XXX_Size() int {
	return xxx_messageInfo_IntType.Size(m)
}
func (m *IntType) XXX_DiscardUnknown() {
	xxx_messageInfo_IntType.DiscardUnknown(m)
}

var xxx_messageInfo_IntType proto.InternalMessageInfo

func (m *IntType) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type DoubleType struct {
	Validator            string   `protobuf:"bytes,1,opt,name=validator,proto3" json:"validator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleType) Reset()         { *m = DoubleType{} }
func (m *DoubleType) String() string { return proto.CompactTextString(m) }
func (*DoubleType) ProtoMessage()    {}
func (*DoubleType) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{7}
}

func (m *DoubleType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleType.Unmarshal(m, b)
}
func (m *DoubleType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleType.Marshal(b, m, deterministic)
}
func (m *DoubleType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleType.Merge(m, src)
}
func (m *DoubleType) XXX_Size() int {
	return xxx_messageInfo_DoubleType.Size(m)
}
func (m *DoubleType) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleType.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleType proto.InternalMessageInfo

func (m *DoubleType) GetValidator() string {
	if m != nil {
		return m.Validator
	}
	return ""
}

type StringValue struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringValue) Reset()         { *m = StringValue{} }
func (m *StringValue) String() string { return proto.CompactTextString(m) }
func (*StringValue) ProtoMessage()    {}
func (*StringValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{8}
}

func (m *StringValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringValue.Unmarshal(m, b)
}
func (m *StringValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringValue.Marshal(b, m, deterministic)
}
func (m *StringValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringValue.Merge(m, src)
}
func (m *StringValue) XXX_Size() int {
	return xxx_messageInfo_StringValue.Size(m)
}
func (m *StringValue) XXX_DiscardUnknown() {
	xxx_messageInfo_StringValue.DiscardUnknown(m)
}

var xxx_messageInfo_StringValue proto.InternalMessageInfo

func (m *StringValue) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type IntValue struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IntValue) Reset()         { *m = IntValue{} }
func (m *IntValue) String() string { return proto.CompactTextString(m) }
func (*IntValue) ProtoMessage()    {}
func (*IntValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{9}
}

func (m *IntValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IntValue.Unmarshal(m, b)
}
func (m *IntValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IntValue.Marshal(b, m, deterministic)
}
func (m *IntValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntValue.Merge(m, src)
}
func (m *IntValue) XXX_Size() int {
	return xxx_messageInfo_IntValue.Size(m)
}
func (m *IntValue) XXX_DiscardUnknown() {
	xxx_messageInfo_IntValue.DiscardUnknown(m)
}

var xxx_messageInfo_IntValue proto.InternalMessageInfo

func (m *IntValue) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type DoubleValue struct {
	Value                int64    `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DoubleValue) Reset()         { *m = DoubleValue{} }
func (m *DoubleValue) String() string { return proto.CompactTextString(m) }
func (*DoubleValue) ProtoMessage()    {}
func (*DoubleValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{10}
}

func (m *DoubleValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DoubleValue.Unmarshal(m, b)
}
func (m *DoubleValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DoubleValue.Marshal(b, m, deterministic)
}
func (m *DoubleValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DoubleValue.Merge(m, src)
}
func (m *DoubleValue) XXX_Size() int {
	return xxx_messageInfo_DoubleValue.Size(m)
}
func (m *DoubleValue) XXX_DiscardUnknown() {
	xxx_messageInfo_DoubleValue.DiscardUnknown(m)
}

var xxx_messageInfo_DoubleValue proto.InternalMessageInfo

func (m *DoubleValue) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_StringValue
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_1b40cafcd4234784, []int{11}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,1,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,3,opt,name=string_value,json=stringValue,proto3,oneof"`
}

func (*Value_IntValue) isValue_Value() {}

func (*Value_DoubleValue) isValue_Value() {}

func (*Value_StringValue) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetIntValue() int64 {
	if x, ok := m.GetValue().(*Value_IntValue); ok {
		return x.IntValue
	}
	return 0
}

func (m *Value) GetDoubleValue() float64 {
	if x, ok := m.GetValue().(*Value_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (m *Value) GetStringValue() string {
	if x, ok := m.GetValue().(*Value_StringValue); ok {
		return x.StringValue
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Value) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_StringValue)(nil),
	}
}

func init() {
	proto.RegisterEnum("api.PropertyType", PropertyType_name, PropertyType_value)
	proto.RegisterType((*Workspace)(nil), "api.Workspace")
	proto.RegisterType((*ArtifactType)(nil), "api.ArtifactType")
	proto.RegisterMapType((map[string]PropertyType)(nil), "api.ArtifactType.PropertiesEntry")
	proto.RegisterType((*ExecutionType)(nil), "api.ExecutionType")
	proto.RegisterMapType((map[string]PropertyType)(nil), "api.ExecutionType.TypePropertiesEntry")
	proto.RegisterType((*Artifact)(nil), "api.Artifact")
	proto.RegisterMapType((map[string]*Value)(nil), "api.Artifact.CustomPropertiesEntry")
	proto.RegisterMapType((map[string]string)(nil), "api.Artifact.LabelsEntry")
	proto.RegisterMapType((map[string]*Value)(nil), "api.Artifact.PropertiesEntry")
	proto.RegisterType((*Execution)(nil), "api.Execution")
	proto.RegisterMapType((map[string]*Value)(nil), "api.Execution.CustomPropertiesEntry")
	proto.RegisterMapType((map[string]string)(nil), "api.Execution.LabelsEntry")
	proto.RegisterMapType((map[string]*Value)(nil), "api.Execution.PropertiesEntry")
	proto.RegisterType((*StringType)(nil), "api.StringType")
	proto.RegisterType((*IntType)(nil), "api.IntType")
	proto.RegisterType((*DoubleType)(nil), "api.DoubleType")
	proto.RegisterType((*StringValue)(nil), "api.StringValue")
	proto.RegisterType((*IntValue)(nil), "api.IntValue")
	proto.RegisterType((*DoubleValue)(nil), "api.DoubleValue")
	proto.RegisterType((*Value)(nil), "api.Value")
}

func init() { proto.RegisterFile("api/api.proto", fileDescriptor_1b40cafcd4234784) }

var fileDescriptor_1b40cafcd4234784 = []byte{
	// 782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0x6d, 0x4f, 0xd3, 0x50,
	0x14, 0xa6, 0x2b, 0x5b, 0xd7, 0xd3, 0x31, 0xc6, 0x55, 0xe3, 0x5c, 0x40, 0xe6, 0x66, 0x84, 0x10,
	0xd3, 0xc5, 0x19, 0x13, 0xf1, 0x2d, 0x01, 0x21, 0xb2, 0x48, 0x36, 0x2c, 0x43, 0x12, 0xbf, 0x2c,
	0x77, 0xed, 0x65, 0xde, 0xb0, 0xb5, 0x4d, 0x7b, 0x0b, 0xee, 0xbf, 0xf8, 0xff, 0x8c, 0xff, 0xc1,
	0x0f, 0xe6, 0xde, 0xee, 0xa5, 0x1d, 0x13, 0xaa, 0x7c, 0xf3, 0xcb, 0xd2, 0x9e, 0xfb, 0x9c, 0xe7,
	0x3c, 0xe7, 0x9e, 0xe7, 0xa4, 0x83, 0x25, 0xec, 0xd2, 0x1a, 0x76, 0xa9, 0xee, 0x7a, 0x0e, 0x73,
	0x90, 0x8c, 0x5d, 0x5a, 0x5a, 0xed, 0x39, 0x4e, 0xaf, 0x4f, 0x6a, 0xe2, 0xc8, 0xb6, 0x1d, 0x86,
	0x19, 0x75, 0x6c, 0x3f, 0x84, 0x94, 0xd6, 0x47, 0xa7, 0xe2, 0xad, 0x1b, 0x9c, 0xd5, 0x18, 0x1d,
	0x10, 0x9f, 0xe1, 0x81, 0x1b, 0x02, 0x2a, 0xeb, 0xa0, 0x9e, 0x3a, 0xde, 0xb9, 0xef, 0x62, 0x93,
	0x20, 0x04, 0x8b, 0x36, 0x1e, 0x90, 0xa2, 0x54, 0x96, 0x36, 0x55, 0x43, 0x3c, 0x57, 0x7e, 0x4a,
	0x90, 0xdb, 0xf1, 0x18, 0x3d, 0xc3, 0x26, 0x6b, 0x0f, 0x5d, 0x82, 0xf2, 0x90, 0xa2, 0x96, 0x80,
	0xc8, 0x46, 0x8a, 0x5a, 0x93, 0xa4, 0xd4, 0x34, 0x09, 0xed, 0x00, 0xb8, 0x9e, 0xe3, 0x12, 0x8f,
	0x51, 0xe2, 0x17, 0xe5, 0xb2, 0xbc, 0xa9, 0xd5, 0x1f, 0xe9, 0x5c, 0x79, 0x94, 0x4a, 0x3f, 0x9a,
	0x60, 0xf6, 0x6d, 0xe6, 0x0d, 0x8d, 0x48, 0x12, 0x2a, 0x83, 0x66, 0x11, 0xdf, 0xf4, 0xa8, 0xcb,
	0xfb, 0x29, 0x2e, 0x0a, 0xf6, 0x68, 0xa8, 0x74, 0x04, 0xcb, 0x33, 0x04, 0xa8, 0x00, 0xf2, 0x39,
	0x19, 0x8e, 0xf4, 0xf3, 0x47, 0xb4, 0x01, 0xe9, 0x0b, 0xdc, 0x0f, 0x42, 0x79, 0xf9, 0xfa, 0x8a,
	0x10, 0x31, 0x4a, 0x1b, 0x72, 0x11, 0x46, 0x78, 0xfe, 0x2a, 0xf5, 0x52, 0xaa, 0xfc, 0x92, 0x60,
	0x69, 0xff, 0x1b, 0x31, 0x03, 0xce, 0x9f, 0xb8, 0xd9, 0x16, 0x2c, 0xb3, 0xa1, 0x4b, 0x3a, 0x57,
	0x3a, 0x7e, 0x22, 0x8a, 0xc5, 0x08, 0x75, 0xfe, 0x33, 0xdb, 0x76, 0x9e, 0xc5, 0x82, 0x09, 0x5a,
	0x6f, 0xc3, 0x9d, 0x39, 0x44, 0xb7, 0x6d, 0xff, 0x7b, 0x1a, 0xb2, 0xe3, 0xf9, 0x5c, 0xe9, 0xfc,
	0x3e, 0x28, 0xa2, 0x4b, 0x6a, 0x09, 0x2e, 0xd9, 0xc8, 0xf0, 0xd7, 0x86, 0xc5, 0x8b, 0x06, 0x1e,
	0x2d, 0xca, 0x61, 0xd1, 0xc0, 0xa3, 0xe8, 0x6d, 0x6c, 0xfa, 0x8b, 0xe2, 0x2e, 0xd6, 0x62, 0xd3,
	0xbf, 0x76, 0xf2, 0x47, 0xb0, 0x62, 0x06, 0x3e, 0x73, 0x06, 0xd1, 0x1b, 0x4d, 0x0b, 0x96, 0x6a,
	0x9c, 0xe5, 0xbd, 0x80, 0xcd, 0x72, 0x15, 0xcc, 0x99, 0xf0, 0x64, 0x6a, 0x99, 0xc8, 0xd4, 0x9e,
	0x82, 0x7a, 0x39, 0x36, 0x7e, 0x51, 0x29, 0x4b, 0x9b, 0x5a, 0x3d, 0x2f, 0xd8, 0x27, 0xeb, 0x60,
	0x4c, 0x01, 0xe8, 0x19, 0x64, 0xfa, 0xb8, 0x4b, 0xfa, 0x7e, 0x31, 0x2b, 0x84, 0x3c, 0x88, 0x0b,
	0x39, 0x14, 0x67, 0x61, 0xf9, 0x11, 0x10, 0xbd, 0x06, 0xcd, 0xf4, 0x08, 0x66, 0xa4, 0xc3, 0x77,
	0xae, 0xa8, 0x8a, 0x12, 0x25, 0x3d, 0x5c, 0x48, 0x7d, 0xbc, 0x90, 0x7a, 0x7b, 0xbc, 0x90, 0x06,
	0x84, 0x70, 0x1e, 0xe0, 0xc9, 0x81, 0x6b, 0x4d, 0x92, 0xe1, 0xe6, 0xe4, 0x10, 0xce, 0x03, 0xa5,
	0x46, 0x92, 0xc5, 0x28, 0x47, 0x9d, 0xa1, 0xd5, 0x41, 0x34, 0xf4, 0x99, 0x47, 0x22, 0x96, 0x28,
	0xb5, 0xe0, 0xde, 0xdc, 0x4b, 0xfe, 0x67, 0xc2, 0x6d, 0xd0, 0x22, 0x97, 0x35, 0x87, 0xe6, 0x6e,
	0x94, 0x46, 0x8d, 0xda, 0xf3, 0x47, 0x1a, 0xd4, 0xc9, 0x32, 0x25, 0xda, 0xcc, 0xd8, 0x8c, 0xe5,
	0x9b, 0x66, 0xfc, 0x6e, 0x8e, 0x6d, 0x1f, 0xc6, 0x57, 0xf8, 0x5a, 0xdf, 0x7e, 0xfa, 0xb3, 0x6f,
	0x1f, 0xcf, 0xd0, 0x24, 0x35, 0x6e, 0x7d, 0x62, 0xbb, 0x8c, 0xe0, 0x29, 0xcd, 0xf0, 0x24, 0xf0,
	0x9d, 0x72, 0x1b, 0xdf, 0x65, 0xff, 0xc6, 0x77, 0x68, 0x1b, 0xc0, 0x67, 0xd8, 0x63, 0x49, 0x0d,
	0xaf, 0x0a, 0xb4, 0x48, 0x7d, 0x01, 0x59, 0x62, 0x5b, 0x49, 0xcd, 0xae, 0x10, 0xdb, 0xfa, 0x9f,
	0x9d, 0xbe, 0x05, 0x70, 0xcc, 0x3c, 0x6a, 0xf7, 0xc4, 0x37, 0x68, 0x15, 0xd4, 0x0b, 0xdc, 0xa7,
	0x16, 0x66, 0x8e, 0x37, 0xca, 0x9f, 0x06, 0x2a, 0x1b, 0xa0, 0x34, 0x6c, 0x96, 0x00, 0xb8, 0x05,
	0xb0, 0xe7, 0x04, 0xdd, 0x3e, 0x49, 0x80, 0xad, 0x82, 0x16, 0x0a, 0x10, 0x5d, 0x4d, 0x95, 0x4a,
	0x11, 0xa5, 0x95, 0x32, 0x64, 0x1b, 0x36, 0x9b, 0x83, 0x90, 0xc7, 0x88, 0x2a, 0x68, 0x61, 0xc9,
	0xeb, 0x40, 0x43, 0x48, 0x87, 0xc7, 0x6b, 0xa0, 0x52, 0x9b, 0x75, 0x22, 0x90, 0x83, 0x05, 0x23,
	0x4b, 0xc7, 0x25, 0xaa, 0x90, 0xb3, 0x04, 0x59, 0x67, 0x7a, 0x6b, 0xd2, 0xc1, 0x82, 0xa1, 0x59,
	0x91, 0x12, 0x55, 0xc8, 0xf9, 0x42, 0xf8, 0x08, 0x24, 0xbe, 0x4a, 0x1c, 0xe4, 0x4f, 0xdb, 0xd9,
	0x55, 0x46, 0x3a, 0xb6, 0xde, 0x40, 0x2e, 0xfa, 0x2d, 0x44, 0x1a, 0x28, 0x27, 0xcd, 0x8f, 0xcd,
	0xd6, 0x69, 0xb3, 0xb0, 0x80, 0x14, 0x90, 0x1b, 0xcd, 0x76, 0x41, 0x42, 0x00, 0x99, 0xbd, 0xd6,
	0xc9, 0xee, 0xe1, 0x7e, 0x21, 0xc5, 0x9f, 0x8f, 0xdb, 0x46, 0xa3, 0xf9, 0xa1, 0x20, 0xef, 0x56,
	0xbe, 0x94, 0x7b, 0x94, 0x7d, 0x0d, 0xba, 0xba, 0xe9, 0x0c, 0x6a, 0xe7, 0x41, 0x97, 0x9c, 0xf5,
	0x9d, 0xcb, 0xda, 0x80, 0x30, 0x6c, 0x61, 0x86, 0xf9, 0x3f, 0xb2, 0x6e, 0x46, 0xb8, 0xf7, 0xf9,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x23, 0xb4, 0x67, 0xba, 0x09, 0x00, 0x00,
}
