// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/service.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/timestamp"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateArtifactTypeRequest struct {
	ArtifactType         *ArtifactType `protobuf:"bytes,1,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateArtifactTypeRequest) Reset()         { *m = CreateArtifactTypeRequest{} }
func (m *CreateArtifactTypeRequest) String() string { return proto.CompactTextString(m) }
func (*CreateArtifactTypeRequest) ProtoMessage()    {}
func (*CreateArtifactTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{0}
}

func (m *CreateArtifactTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArtifactTypeRequest.Unmarshal(m, b)
}
func (m *CreateArtifactTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArtifactTypeRequest.Marshal(b, m, deterministic)
}
func (m *CreateArtifactTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArtifactTypeRequest.Merge(m, src)
}
func (m *CreateArtifactTypeRequest) XXX_Size() int {
	return xxx_messageInfo_CreateArtifactTypeRequest.Size(m)
}
func (m *CreateArtifactTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArtifactTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArtifactTypeRequest proto.InternalMessageInfo

func (m *CreateArtifactTypeRequest) GetArtifactType() *ArtifactType {
	if m != nil {
		return m.ArtifactType
	}
	return nil
}

type CreateArtifactTypeResponse struct {
	ArtifactType         *ArtifactType `protobuf:"bytes,1,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CreateArtifactTypeResponse) Reset()         { *m = CreateArtifactTypeResponse{} }
func (m *CreateArtifactTypeResponse) String() string { return proto.CompactTextString(m) }
func (*CreateArtifactTypeResponse) ProtoMessage()    {}
func (*CreateArtifactTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{1}
}

func (m *CreateArtifactTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArtifactTypeResponse.Unmarshal(m, b)
}
func (m *CreateArtifactTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArtifactTypeResponse.Marshal(b, m, deterministic)
}
func (m *CreateArtifactTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArtifactTypeResponse.Merge(m, src)
}
func (m *CreateArtifactTypeResponse) XXX_Size() int {
	return xxx_messageInfo_CreateArtifactTypeResponse.Size(m)
}
func (m *CreateArtifactTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArtifactTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArtifactTypeResponse proto.InternalMessageInfo

func (m *CreateArtifactTypeResponse) GetArtifactType() *ArtifactType {
	if m != nil {
		return m.ArtifactType
	}
	return nil
}

type GetArtifactTypeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArtifactTypeRequest) Reset()         { *m = GetArtifactTypeRequest{} }
func (m *GetArtifactTypeRequest) String() string { return proto.CompactTextString(m) }
func (*GetArtifactTypeRequest) ProtoMessage()    {}
func (*GetArtifactTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{2}
}

func (m *GetArtifactTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArtifactTypeRequest.Unmarshal(m, b)
}
func (m *GetArtifactTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArtifactTypeRequest.Marshal(b, m, deterministic)
}
func (m *GetArtifactTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArtifactTypeRequest.Merge(m, src)
}
func (m *GetArtifactTypeRequest) XXX_Size() int {
	return xxx_messageInfo_GetArtifactTypeRequest.Size(m)
}
func (m *GetArtifactTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArtifactTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArtifactTypeRequest proto.InternalMessageInfo

func (m *GetArtifactTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetArtifactTypeResponse struct {
	ArtifactType         *ArtifactType `protobuf:"bytes,1,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetArtifactTypeResponse) Reset()         { *m = GetArtifactTypeResponse{} }
func (m *GetArtifactTypeResponse) String() string { return proto.CompactTextString(m) }
func (*GetArtifactTypeResponse) ProtoMessage()    {}
func (*GetArtifactTypeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{3}
}

func (m *GetArtifactTypeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArtifactTypeResponse.Unmarshal(m, b)
}
func (m *GetArtifactTypeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArtifactTypeResponse.Marshal(b, m, deterministic)
}
func (m *GetArtifactTypeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArtifactTypeResponse.Merge(m, src)
}
func (m *GetArtifactTypeResponse) XXX_Size() int {
	return xxx_messageInfo_GetArtifactTypeResponse.Size(m)
}
func (m *GetArtifactTypeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArtifactTypeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArtifactTypeResponse proto.InternalMessageInfo

func (m *GetArtifactTypeResponse) GetArtifactType() *ArtifactType {
	if m != nil {
		return m.ArtifactType
	}
	return nil
}

type ListArtifactTypesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArtifactTypesRequest) Reset()         { *m = ListArtifactTypesRequest{} }
func (m *ListArtifactTypesRequest) String() string { return proto.CompactTextString(m) }
func (*ListArtifactTypesRequest) ProtoMessage()    {}
func (*ListArtifactTypesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{4}
}

func (m *ListArtifactTypesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArtifactTypesRequest.Unmarshal(m, b)
}
func (m *ListArtifactTypesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArtifactTypesRequest.Marshal(b, m, deterministic)
}
func (m *ListArtifactTypesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArtifactTypesRequest.Merge(m, src)
}
func (m *ListArtifactTypesRequest) XXX_Size() int {
	return xxx_messageInfo_ListArtifactTypesRequest.Size(m)
}
func (m *ListArtifactTypesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArtifactTypesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListArtifactTypesRequest proto.InternalMessageInfo

type ListArtifactTypesResponse struct {
	ArtifactTypes        []*ArtifactType `protobuf:"bytes,1,rep,name=artifact_types,json=artifactTypes,proto3" json:"artifact_types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListArtifactTypesResponse) Reset()         { *m = ListArtifactTypesResponse{} }
func (m *ListArtifactTypesResponse) String() string { return proto.CompactTextString(m) }
func (*ListArtifactTypesResponse) ProtoMessage()    {}
func (*ListArtifactTypesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{5}
}

func (m *ListArtifactTypesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArtifactTypesResponse.Unmarshal(m, b)
}
func (m *ListArtifactTypesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArtifactTypesResponse.Marshal(b, m, deterministic)
}
func (m *ListArtifactTypesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArtifactTypesResponse.Merge(m, src)
}
func (m *ListArtifactTypesResponse) XXX_Size() int {
	return xxx_messageInfo_ListArtifactTypesResponse.Size(m)
}
func (m *ListArtifactTypesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArtifactTypesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListArtifactTypesResponse proto.InternalMessageInfo

func (m *ListArtifactTypesResponse) GetArtifactTypes() []*ArtifactType {
	if m != nil {
		return m.ArtifactTypes
	}
	return nil
}

type DeleteArtifactTypeRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteArtifactTypeRequest) Reset()         { *m = DeleteArtifactTypeRequest{} }
func (m *DeleteArtifactTypeRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteArtifactTypeRequest) ProtoMessage()    {}
func (*DeleteArtifactTypeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{6}
}

func (m *DeleteArtifactTypeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteArtifactTypeRequest.Unmarshal(m, b)
}
func (m *DeleteArtifactTypeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteArtifactTypeRequest.Marshal(b, m, deterministic)
}
func (m *DeleteArtifactTypeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteArtifactTypeRequest.Merge(m, src)
}
func (m *DeleteArtifactTypeRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteArtifactTypeRequest.Size(m)
}
func (m *DeleteArtifactTypeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteArtifactTypeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteArtifactTypeRequest proto.InternalMessageInfo

func (m *DeleteArtifactTypeRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateArtifactRequest struct {
	Parent               string    `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Artifact             *Artifact `protobuf:"bytes,2,opt,name=artifact,proto3" json:"artifact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateArtifactRequest) Reset()         { *m = CreateArtifactRequest{} }
func (m *CreateArtifactRequest) String() string { return proto.CompactTextString(m) }
func (*CreateArtifactRequest) ProtoMessage()    {}
func (*CreateArtifactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{7}
}

func (m *CreateArtifactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArtifactRequest.Unmarshal(m, b)
}
func (m *CreateArtifactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArtifactRequest.Marshal(b, m, deterministic)
}
func (m *CreateArtifactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArtifactRequest.Merge(m, src)
}
func (m *CreateArtifactRequest) XXX_Size() int {
	return xxx_messageInfo_CreateArtifactRequest.Size(m)
}
func (m *CreateArtifactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArtifactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArtifactRequest proto.InternalMessageInfo

func (m *CreateArtifactRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateArtifactRequest) GetArtifact() *Artifact {
	if m != nil {
		return m.Artifact
	}
	return nil
}

type CreateArtifactResponse struct {
	Artifact             *Artifact `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CreateArtifactResponse) Reset()         { *m = CreateArtifactResponse{} }
func (m *CreateArtifactResponse) String() string { return proto.CompactTextString(m) }
func (*CreateArtifactResponse) ProtoMessage()    {}
func (*CreateArtifactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{8}
}

func (m *CreateArtifactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateArtifactResponse.Unmarshal(m, b)
}
func (m *CreateArtifactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateArtifactResponse.Marshal(b, m, deterministic)
}
func (m *CreateArtifactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateArtifactResponse.Merge(m, src)
}
func (m *CreateArtifactResponse) XXX_Size() int {
	return xxx_messageInfo_CreateArtifactResponse.Size(m)
}
func (m *CreateArtifactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateArtifactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateArtifactResponse proto.InternalMessageInfo

func (m *CreateArtifactResponse) GetArtifact() *Artifact {
	if m != nil {
		return m.Artifact
	}
	return nil
}

type GetArtifactRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetArtifactRequest) Reset()         { *m = GetArtifactRequest{} }
func (m *GetArtifactRequest) String() string { return proto.CompactTextString(m) }
func (*GetArtifactRequest) ProtoMessage()    {}
func (*GetArtifactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{9}
}

func (m *GetArtifactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArtifactRequest.Unmarshal(m, b)
}
func (m *GetArtifactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArtifactRequest.Marshal(b, m, deterministic)
}
func (m *GetArtifactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArtifactRequest.Merge(m, src)
}
func (m *GetArtifactRequest) XXX_Size() int {
	return xxx_messageInfo_GetArtifactRequest.Size(m)
}
func (m *GetArtifactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArtifactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetArtifactRequest proto.InternalMessageInfo

func (m *GetArtifactRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetArtifactResponse struct {
	Artifact             *Artifact `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetArtifactResponse) Reset()         { *m = GetArtifactResponse{} }
func (m *GetArtifactResponse) String() string { return proto.CompactTextString(m) }
func (*GetArtifactResponse) ProtoMessage()    {}
func (*GetArtifactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{10}
}

func (m *GetArtifactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetArtifactResponse.Unmarshal(m, b)
}
func (m *GetArtifactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetArtifactResponse.Marshal(b, m, deterministic)
}
func (m *GetArtifactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetArtifactResponse.Merge(m, src)
}
func (m *GetArtifactResponse) XXX_Size() int {
	return xxx_messageInfo_GetArtifactResponse.Size(m)
}
func (m *GetArtifactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetArtifactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetArtifactResponse proto.InternalMessageInfo

func (m *GetArtifactResponse) GetArtifact() *Artifact {
	if m != nil {
		return m.Artifact
	}
	return nil
}

type ListArtifactsRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListArtifactsRequest) Reset()         { *m = ListArtifactsRequest{} }
func (m *ListArtifactsRequest) String() string { return proto.CompactTextString(m) }
func (*ListArtifactsRequest) ProtoMessage()    {}
func (*ListArtifactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{11}
}

func (m *ListArtifactsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArtifactsRequest.Unmarshal(m, b)
}
func (m *ListArtifactsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArtifactsRequest.Marshal(b, m, deterministic)
}
func (m *ListArtifactsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArtifactsRequest.Merge(m, src)
}
func (m *ListArtifactsRequest) XXX_Size() int {
	return xxx_messageInfo_ListArtifactsRequest.Size(m)
}
func (m *ListArtifactsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArtifactsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListArtifactsRequest proto.InternalMessageInfo

func (m *ListArtifactsRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListArtifactsResponse struct {
	Artifacts            []*Artifact `protobuf:"bytes,1,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ListArtifactsResponse) Reset()         { *m = ListArtifactsResponse{} }
func (m *ListArtifactsResponse) String() string { return proto.CompactTextString(m) }
func (*ListArtifactsResponse) ProtoMessage()    {}
func (*ListArtifactsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{12}
}

func (m *ListArtifactsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListArtifactsResponse.Unmarshal(m, b)
}
func (m *ListArtifactsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListArtifactsResponse.Marshal(b, m, deterministic)
}
func (m *ListArtifactsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListArtifactsResponse.Merge(m, src)
}
func (m *ListArtifactsResponse) XXX_Size() int {
	return xxx_messageInfo_ListArtifactsResponse.Size(m)
}
func (m *ListArtifactsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListArtifactsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListArtifactsResponse proto.InternalMessageInfo

func (m *ListArtifactsResponse) GetArtifacts() []*Artifact {
	if m != nil {
		return m.Artifacts
	}
	return nil
}

type DeleteArtifactRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteArtifactRequest) Reset()         { *m = DeleteArtifactRequest{} }
func (m *DeleteArtifactRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteArtifactRequest) ProtoMessage()    {}
func (*DeleteArtifactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_42c32aec9010f89c, []int{13}
}

func (m *DeleteArtifactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteArtifactRequest.Unmarshal(m, b)
}
func (m *DeleteArtifactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteArtifactRequest.Marshal(b, m, deterministic)
}
func (m *DeleteArtifactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteArtifactRequest.Merge(m, src)
}
func (m *DeleteArtifactRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteArtifactRequest.Size(m)
}
func (m *DeleteArtifactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteArtifactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteArtifactRequest proto.InternalMessageInfo

func (m *DeleteArtifactRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateArtifactTypeRequest)(nil), "api.CreateArtifactTypeRequest")
	proto.RegisterType((*CreateArtifactTypeResponse)(nil), "api.CreateArtifactTypeResponse")
	proto.RegisterType((*GetArtifactTypeRequest)(nil), "api.GetArtifactTypeRequest")
	proto.RegisterType((*GetArtifactTypeResponse)(nil), "api.GetArtifactTypeResponse")
	proto.RegisterType((*ListArtifactTypesRequest)(nil), "api.ListArtifactTypesRequest")
	proto.RegisterType((*ListArtifactTypesResponse)(nil), "api.ListArtifactTypesResponse")
	proto.RegisterType((*DeleteArtifactTypeRequest)(nil), "api.DeleteArtifactTypeRequest")
	proto.RegisterType((*CreateArtifactRequest)(nil), "api.CreateArtifactRequest")
	proto.RegisterType((*CreateArtifactResponse)(nil), "api.CreateArtifactResponse")
	proto.RegisterType((*GetArtifactRequest)(nil), "api.GetArtifactRequest")
	proto.RegisterType((*GetArtifactResponse)(nil), "api.GetArtifactResponse")
	proto.RegisterType((*ListArtifactsRequest)(nil), "api.ListArtifactsRequest")
	proto.RegisterType((*ListArtifactsResponse)(nil), "api.ListArtifactsResponse")
	proto.RegisterType((*DeleteArtifactRequest)(nil), "api.DeleteArtifactRequest")
}

func init() { proto.RegisterFile("api/service.proto", fileDescriptor_42c32aec9010f89c) }

var fileDescriptor_42c32aec9010f89c = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5d, 0x6f, 0x12, 0x41,
	0x14, 0xcd, 0xb6, 0xa6, 0x69, 0x6f, 0xa5, 0x0d, 0xa3, 0x50, 0x58, 0x90, 0x92, 0x8d, 0xc6, 0x4a,
	0xed, 0x6e, 0x28, 0x89, 0x1f, 0x4d, 0x9a, 0xa8, 0xd4, 0xf8, 0xa2, 0x0f, 0xd2, 0xfa, 0xd2, 0x17,
	0x33, 0xe0, 0x40, 0x37, 0xb2, 0x1f, 0x32, 0x43, 0x95, 0x10, 0xd3, 0xc4, 0x47, 0x1f, 0x7c, 0xf1,
	0x1f, 0xf8, 0x97, 0xfc, 0x0b, 0xfe, 0x10, 0xb3, 0xb3, 0xb3, 0xb0, 0xb3, 0x3b, 0x4b, 0xa8, 0xbe,
	0x31, 0x73, 0x86, 0x7b, 0xce, 0xbd, 0x67, 0xcf, 0x85, 0x3c, 0xf6, 0x6d, 0x8b, 0x92, 0xd1, 0xa5,
	0xdd, 0x23, 0xa6, 0x3f, 0xf2, 0x98, 0x87, 0x56, 0xb1, 0x6f, 0xeb, 0xb9, 0xe0, 0x1e, 0xfb, 0x76,
	0x78, 0xa7, 0x57, 0x07, 0x9e, 0x37, 0x18, 0x12, 0x8b, 0xdf, 0xba, 0xae, 0xc7, 0x30, 0xb3, 0x3d,
	0x97, 0x0a, 0xb4, 0x22, 0x50, 0x7e, 0xea, 0x8e, 0xfb, 0x16, 0x71, 0x7c, 0x36, 0x11, 0xe0, 0x6e,
	0x12, 0x64, 0xb6, 0x43, 0x28, 0xc3, 0x8e, 0x1f, 0x3e, 0x30, 0x4e, 0xa1, 0xdc, 0x1e, 0x11, 0xcc,
	0xc8, 0xf3, 0x11, 0xb3, 0xfb, 0xb8, 0xc7, 0xce, 0x26, 0x3e, 0xe9, 0x90, 0x4f, 0x63, 0x42, 0x19,
	0x7a, 0x04, 0x39, 0x2c, 0xae, 0xdf, 0xb3, 0x89, 0x4f, 0x4a, 0x5a, 0x5d, 0xdb, 0xdb, 0x3c, 0xcc,
	0x9b, 0x81, 0x36, 0xe9, 0x0f, 0x37, 0x71, 0xec, 0x64, 0x9c, 0x81, 0xae, 0x2a, 0x4a, 0x7d, 0xcf,
	0xa5, 0xe4, 0x9f, 0xab, 0x3e, 0x84, 0xe2, 0x2b, 0xc2, 0x54, 0x3a, 0x11, 0xdc, 0x70, 0xb1, 0x13,
	0x16, 0xda, 0xe8, 0xf0, 0xdf, 0xc6, 0x5b, 0xd8, 0x49, 0xbd, 0xfe, 0x4f, 0x01, 0x3a, 0x94, 0x5e,
	0xdb, 0x54, 0xaa, 0x49, 0x85, 0x04, 0xe3, 0x1d, 0x94, 0x15, 0x98, 0x20, 0x7c, 0x02, 0x5b, 0x12,
	0x21, 0x2d, 0x69, 0xf5, 0x55, 0x35, 0x63, 0x2e, 0xce, 0x48, 0x0d, 0x0b, 0xca, 0x27, 0x64, 0x48,
	0xd4, 0xf6, 0xa8, 0xda, 0x3e, 0x87, 0x82, 0x3c, 0xfa, 0xe8, 0x71, 0x11, 0xd6, 0x7c, 0x3c, 0x22,
	0x2e, 0x13, 0xcf, 0xc5, 0x09, 0x3d, 0x80, 0xf5, 0x88, 0xb2, 0xb4, 0xc2, 0xe7, 0x90, 0x93, 0x54,
	0x75, 0x66, 0xb0, 0xd1, 0x86, 0x62, 0xb2, 0xb6, 0x68, 0x30, 0x5e, 0x44, 0x5b, 0x5c, 0x64, 0x0f,
	0x50, 0xcc, 0x97, 0x45, 0xad, 0x3c, 0x83, 0x5b, 0xd2, 0xcb, 0xeb, 0x73, 0x35, 0xe0, 0x76, 0xdc,
	0x14, 0xba, 0x88, 0xed, 0x04, 0x0a, 0x89, 0xb7, 0x82, 0x6f, 0x1f, 0x36, 0xa2, 0x82, 0x91, 0x6f,
	0x09, 0xc2, 0x39, 0x6e, 0xec, 0x43, 0x41, 0xf6, 0x6b, 0x01, 0xe5, 0xe1, 0xaf, 0x75, 0xd8, 0x7e,
	0x43, 0x18, 0xfe, 0x80, 0x19, 0x3e, 0x0d, 0xb7, 0x00, 0xfa, 0xae, 0x01, 0x4a, 0x67, 0x07, 0xd5,
	0x38, 0x63, 0x66, 0x52, 0xf5, 0xdd, 0x4c, 0x3c, 0xec, 0xc2, 0x68, 0x7d, 0xfb, 0xfd, 0xe7, 0xe7,
	0xca, 0x81, 0x51, 0xe5, 0x5b, 0xe4, 0xb2, 0x89, 0x87, 0xfe, 0x05, 0x6e, 0x5a, 0xf2, 0x67, 0x79,
	0x24, 0xe7, 0x02, 0x4d, 0x61, 0x3b, 0x91, 0x21, 0x54, 0xe1, 0x44, 0xea, 0x1c, 0xea, 0x55, 0x35,
	0x28, 0x24, 0x1c, 0x70, 0x09, 0xf7, 0xd1, 0x3d, 0x59, 0xc2, 0x34, 0x98, 0xc5, 0xb1, 0x2c, 0xc4,
	0x6a, 0x7c, 0x45, 0x5f, 0x20, 0x9f, 0x4a, 0x14, 0xba, 0xc3, 0x19, 0xb2, 0x52, 0xa8, 0xd7, 0xb2,
	0x60, 0x21, 0xe1, 0x2e, 0x97, 0x50, 0x43, 0x0b, 0xa7, 0x80, 0xa6, 0x80, 0xd2, 0xa1, 0x13, 0x16,
	0x64, 0xa6, 0x51, 0x2f, 0x9a, 0xe1, 0xae, 0x35, 0xa3, 0x5d, 0x6b, 0xbe, 0x0c, 0x16, 0x71, 0xd4,
	0x76, 0x63, 0xc9, 0xb6, 0x7f, 0x68, 0xb0, 0x25, 0xfb, 0x88, 0x74, 0x85, 0xb9, 0x11, 0x6b, 0x45,
	0x89, 0x89, 0x76, 0xdb, 0x9c, 0xfa, 0xd8, 0x68, 0x26, 0xa8, 0xc3, 0xe8, 0xa7, 0xc9, 0x67, 0x83,
	0xa0, 0x47, 0xb3, 0x10, 0xa1, 0x29, 0x6c, 0xc6, 0x1c, 0x45, 0x3b, 0x49, 0x8f, 0x23, 0x25, 0xa5,
	0x34, 0x20, 0x64, 0x3c, 0xe5, 0x32, 0x5a, 0xa8, 0xb9, 0xcc, 0x04, 0xe6, 0x1a, 0x82, 0x69, 0x5c,
	0x41, 0x4e, 0x4a, 0x25, 0x2a, 0xa7, 0x1c, 0x9e, 0x99, 0xaf, 0xab, 0x20, 0x21, 0xe1, 0x31, 0x97,
	0xd0, 0x44, 0xd6, 0x52, 0x26, 0xcc, 0x35, 0xa0, 0x2b, 0xd8, 0x92, 0x2d, 0x17, 0x6e, 0x28, 0x53,
	0x9e, 0xf9, 0x0d, 0x88, 0x09, 0x34, 0xae, 0x3f, 0x81, 0x17, 0xc6, 0x79, 0x7d, 0x60, 0xb3, 0x8b,
	0x71, 0xd7, 0xec, 0x79, 0x8e, 0xf5, 0x71, 0xdc, 0x25, 0xfd, 0xa1, 0xf7, 0xd9, 0x72, 0xc4, 0xde,
	0x08, 0x0a, 0x76, 0xd7, 0x38, 0x5d, 0xeb, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x92, 0xeb, 0xb5,
	0x63, 0x50, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetadataServiceClient is the client API for MetadataService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetadataServiceClient interface {
	CreateArtifactType(ctx context.Context, in *CreateArtifactTypeRequest, opts ...grpc.CallOption) (*CreateArtifactTypeResponse, error)
	GetArtifactType(ctx context.Context, in *GetArtifactTypeRequest, opts ...grpc.CallOption) (*GetArtifactTypeResponse, error)
	ListArtifactTypes(ctx context.Context, in *ListArtifactTypesRequest, opts ...grpc.CallOption) (*ListArtifactTypesResponse, error)
	DeleteArtifactType(ctx context.Context, in *DeleteArtifactTypeRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	CreateArtifact(ctx context.Context, in *CreateArtifactRequest, opts ...grpc.CallOption) (*CreateArtifactResponse, error)
	GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*GetArtifactResponse, error)
	ListArtifacts(ctx context.Context, in *ListArtifactsRequest, opts ...grpc.CallOption) (*ListArtifactsResponse, error)
	DeleteArtifact(ctx context.Context, in *DeleteArtifactRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type metadataServiceClient struct {
	cc *grpc.ClientConn
}

func NewMetadataServiceClient(cc *grpc.ClientConn) MetadataServiceClient {
	return &metadataServiceClient{cc}
}

func (c *metadataServiceClient) CreateArtifactType(ctx context.Context, in *CreateArtifactTypeRequest, opts ...grpc.CallOption) (*CreateArtifactTypeResponse, error) {
	out := new(CreateArtifactTypeResponse)
	err := c.cc.Invoke(ctx, "/api.MetadataService/CreateArtifactType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetArtifactType(ctx context.Context, in *GetArtifactTypeRequest, opts ...grpc.CallOption) (*GetArtifactTypeResponse, error) {
	out := new(GetArtifactTypeResponse)
	err := c.cc.Invoke(ctx, "/api.MetadataService/GetArtifactType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListArtifactTypes(ctx context.Context, in *ListArtifactTypesRequest, opts ...grpc.CallOption) (*ListArtifactTypesResponse, error) {
	out := new(ListArtifactTypesResponse)
	err := c.cc.Invoke(ctx, "/api.MetadataService/ListArtifactTypes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) DeleteArtifactType(ctx context.Context, in *DeleteArtifactTypeRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.MetadataService/DeleteArtifactType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) CreateArtifact(ctx context.Context, in *CreateArtifactRequest, opts ...grpc.CallOption) (*CreateArtifactResponse, error) {
	out := new(CreateArtifactResponse)
	err := c.cc.Invoke(ctx, "/api.MetadataService/CreateArtifact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) GetArtifact(ctx context.Context, in *GetArtifactRequest, opts ...grpc.CallOption) (*GetArtifactResponse, error) {
	out := new(GetArtifactResponse)
	err := c.cc.Invoke(ctx, "/api.MetadataService/GetArtifact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) ListArtifacts(ctx context.Context, in *ListArtifactsRequest, opts ...grpc.CallOption) (*ListArtifactsResponse, error) {
	out := new(ListArtifactsResponse)
	err := c.cc.Invoke(ctx, "/api.MetadataService/ListArtifacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metadataServiceClient) DeleteArtifact(ctx context.Context, in *DeleteArtifactRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/api.MetadataService/DeleteArtifact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetadataServiceServer is the server API for MetadataService service.
type MetadataServiceServer interface {
	CreateArtifactType(context.Context, *CreateArtifactTypeRequest) (*CreateArtifactTypeResponse, error)
	GetArtifactType(context.Context, *GetArtifactTypeRequest) (*GetArtifactTypeResponse, error)
	ListArtifactTypes(context.Context, *ListArtifactTypesRequest) (*ListArtifactTypesResponse, error)
	DeleteArtifactType(context.Context, *DeleteArtifactTypeRequest) (*empty.Empty, error)
	CreateArtifact(context.Context, *CreateArtifactRequest) (*CreateArtifactResponse, error)
	GetArtifact(context.Context, *GetArtifactRequest) (*GetArtifactResponse, error)
	ListArtifacts(context.Context, *ListArtifactsRequest) (*ListArtifactsResponse, error)
	DeleteArtifact(context.Context, *DeleteArtifactRequest) (*empty.Empty, error)
}

func RegisterMetadataServiceServer(s *grpc.Server, srv MetadataServiceServer) {
	s.RegisterService(&_MetadataService_serviceDesc, srv)
}

func _MetadataService_CreateArtifactType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArtifactTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateArtifactType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/CreateArtifactType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateArtifactType(ctx, req.(*CreateArtifactTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetArtifactType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetArtifactType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/GetArtifactType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetArtifactType(ctx, req.(*GetArtifactTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListArtifactTypes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtifactTypesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListArtifactTypes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/ListArtifactTypes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListArtifactTypes(ctx, req.(*ListArtifactTypesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_DeleteArtifactType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArtifactTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteArtifactType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/DeleteArtifactType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteArtifactType(ctx, req.(*DeleteArtifactTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_CreateArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).CreateArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/CreateArtifact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).CreateArtifact(ctx, req.(*CreateArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_GetArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).GetArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/GetArtifact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).GetArtifact(ctx, req.(*GetArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_ListArtifacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArtifactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).ListArtifacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/ListArtifacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).ListArtifacts(ctx, req.(*ListArtifactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetadataService_DeleteArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetadataServiceServer).DeleteArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.MetadataService/DeleteArtifact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetadataServiceServer).DeleteArtifact(ctx, req.(*DeleteArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MetadataService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.MetadataService",
	HandlerType: (*MetadataServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateArtifactType",
			Handler:    _MetadataService_CreateArtifactType_Handler,
		},
		{
			MethodName: "GetArtifactType",
			Handler:    _MetadataService_GetArtifactType_Handler,
		},
		{
			MethodName: "ListArtifactTypes",
			Handler:    _MetadataService_ListArtifactTypes_Handler,
		},
		{
			MethodName: "DeleteArtifactType",
			Handler:    _MetadataService_DeleteArtifactType_Handler,
		},
		{
			MethodName: "CreateArtifact",
			Handler:    _MetadataService_CreateArtifact_Handler,
		},
		{
			MethodName: "GetArtifact",
			Handler:    _MetadataService_GetArtifact_Handler,
		},
		{
			MethodName: "ListArtifacts",
			Handler:    _MetadataService_ListArtifacts_Handler,
		},
		{
			MethodName: "DeleteArtifact",
			Handler:    _MetadataService_DeleteArtifact_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/service.proto",
}
